
--CRIAÇÃO DA TABELA
CREATE TABLE TABELA_PROCEDURES (ID_PROCEDURE NUMBER,
NOME_PROCEDURE VARCHAR2(30),
DATA_CRIACAO DATE,
CREATE_USER VARCHAR2(30));

CREATE SEQUENCE SQ_PROCEDURE;
INSERT INTO TABELA_PROCEDURES VALUES(SQ_PROCEDURE.NEXTVAL,'PRIMEIRA PROCEDURE', SYSDATE, 'VERGS');
COMMIT;

SELECT * FROM tabela_procedures

--CRIAÇÃO DA PROCEDURE 

CREATE OR REPLACE PROCEDURE PROCEDURE_INSERT(
V_1 VARCHAR2,
V_2 DATE ,
V_3 VARCHAR2) AS
BEGIN
INSERT INTO TABELA_PROCEDURES VALUES(
SQ_PROCEDURE.NEXTVAL,
V_1,
v_2,
V_3);
COMMIT;
END PROCEDURE_INSERT;

--UTILIZAÇÃO DA PROCEDURE
CALL procedure_insert('procedure delete', sysdate, 'maria');
SELECT * FROM TABELA_PROCEDURES
